services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - mssql-network

volumes:
  sqlserver-data:
    driver: local
    name: sqlserver-data

networks:
  mssql-network:
    name: mssql-network
    driver: bridge